version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: ongaku
    ports:
      - '5432:5432'
  web:
    image: ongaku-api
    depends_on:
      - db
    ports:
      - '3001:3001'
